### ISSUE TITLE
DCMM with No Regressors Not Possible

### ISSUE THREAD

**Issue by bking124** [lavinei/pybats#11]
Dear Isaac,

First off, I'm so glad this package exists and it has lots of cool features.  I am currently looking at univariate count data with lots of zeroes and wanted to compare the Poisson DGLM forecasting performance with that of a DCMM.  However, it seems that currently the analysis_dcmm function requires some input for the covariates X, and inputting None (like the default in the regular analysis function) throws an error of 'NoneType object not subscriptable'.  I was able to 'monkey patch' a few of the functions in the package to get it to work for my case, but I think this is a capability that would probably be desirable for others.

I can create a reproducible example of the error if needed!  Thanks!

Sincerely,
Brian

**Comment by lavinei** [comment]
Hi Brian,

Thank you for using Pybats. You're right, analysis_dcmm was configured to require real valued predictors X. I've just implemented a fix, which is available in the newest version on pypi (pybats v. 0.0.5) or with the latest code on Github. Please let me know if this works for you!

Thanks,
 Isaac
