### ISSUE TITLE
Update and Forecast Model - ValueError: p < 0, p > 1 or p contains NaNs

### ISSUE THREAD

**Issue by niserson** [lavinei/pybats#2]
Hello, Lavinei,

I've decided to apply your approach to my own data and had no success with the error above:

/usr/local/lib/python3.6/dist-packages/pybats/dglm.py in simulate_from_sampling_model(self, p, nsamps)
    415 
    416     def simulate_from_sampling_model(self, p, nsamps):
--> 417         return np.random.binomial(1, p, [nsamps])
    418 
    419     def simulate_from_prior(self, alpha, beta, nsamps):

mtrand.pyx in numpy.random.mtrand.RandomState.binomial()

_common.pyx in numpy.random._common.check_array_constraint()

ValueError: p < 0, p > 1 or p contains NaNs

Link to the code: https://colab.research.google.com/drive/1_5LHVy1_EHRoohPhk8Dk26xTnVLooCRS?usp=sharing
I could send you the data by email, if it is possible.

Thanks!

Regards,
Nikita

**Comment by lavinei** [comment]
Hi Nikita,

I apologize for the late reply, I didn't see this issue until today. I'd be happy to take a look at your data and work through the issue with you, if you'd like to send it to me at lavine.isaac@gmail.com.

Thanks,
 Isaac

**Comment by niserson** [comment]
Hi Isaac,

thanks for getting back to me, no problem..! I've solved the problem, I
suppose there were not enough non-zero observations to define priors in
Dynamic Count Mixture Models.
I've just increased the horizon of priors and changed the model granularity
from daily to hourly and it started working. The link to the notebook is
here, but it is only first test I did:
https://colab.research.google.com/drive/1FIKBvpP_NsDpXgaqL1D_9WsrvIFhTCNB?usp=sharing

Now I've tried your library with wide range of data, including two-year
daily data of Nederlands grocery retail company. We've added weather
features, calendar events features, Google Mobility and Containment
Measures and Restrictions for COVID-19 period, and it worked very well,
thank you very much..!

We are thinking now about integrating item-interactions features
(complementary/substitution) effects, but we are not sure yet which
approach to take. It seems that SHOPPER model is state-of-the-art:
https://humboldt-wi.github.io/blog/research/information_systems_1920/group3_shopper/
https://github.com/franrruiz/shopper-src

Two questions - if you don't mind:
1. Do you know other good approaches to integrate item-interaction effects
in forecasting models..?
2. Is it possible to contribute/support/maintain/develop your package
further together with you/your scientific advisors (if you have other
priorities, for example)..?

Thank you for your valuable time, efforts and attention - and for the great
work as well..!

*Regards,*
*Nikita Iserson*
*+49(151)-114-05-700*


вс, 25 окт. 2020 г. в 14:34, lavinei <notifications@github.com>:

**Comment by lavinei** [comment]
Hi Nikita,

Thanks for your response, I'm glad that you've been using the package and that it's working well for you! Item-interaction effects are an interesting question, it's something that I thought about a little bit, but never had the opportunity to work on much.

If you'd like to work with something that already exists within PyBATS, I'd recommend using latent factors to capture interactions among items. The [latent factor](https://lavinei.github.io/pybats/latent_factor.html) is a regression predictor that is a random variable. To give an example of using a latent factor, this [paper](https://arxiv.org/pdf/2007.04956.pdf) uses a model on total sales to create a latent factor which is a forecast of day-of-week and holiday effects. If the same latent factor is used in multiple item models, then there will be dependence in the forecast. You can model the joint forecast distribution across items either with a Copula model using [this function](https://lavinei.github.io/pybats/latent_factor_fxns.html#Multivariate-forecasting-with-multiple-DCMMs), or by simulating the latent factor, as is done in this [paper](https://arxiv.org/pdf/1805.05232.pdf).

To focus on item-interactions in particular, here is one simple idea: Simulate from the forecast distribution of one item, and then use those simulated values as predictors for another item. Pybats has functions to work with these simulated values, in [this module](https://lavinei.github.io/pybats/latent_factor_fxns.html#Simulation-based-latent-factor-analysis).

In terms of developing PyBATS further, I would love to have you and others contribute to the package! I am no longer in graduate school, so I don't have as much time to actively develop, but I can certainly help out if there are things you would like to add. Please let me know if you have ideas for additional models, and feel free to submit pull requests.

Best,
 Isaac
