### ISSUE TITLE
How to actually forecast?

### ISSUE THREAD

**Issue by artrune** [lavinei/pybats#6]
When tested with the examples it works beautifully but whenever asked to forecast more data than available it doesn't do anything.

Am I missing something or should i use the generated model for that.

**Comment by lavinei** [comment]
Hi Aguilar,

Yes, you should use the generated model to forecast past the end of your dataset.

The analysis function provides out-of-sample forecasts on the dataset provided, and returns the final model after updating through the specified 'forecast_end' time step. Take this model and use the forecast_marginal() or forecast_path() functions to forecast beyond the end of the dataset. Note that you'll need to provide the model with the predictors (X) into the future.

Thanks,
 Isaac

**Comment by artrune** [comment]
Thanks, that makes sense!

What would be the difference between forecast_path and marginal, in theory?

**Comment by lavinei** [comment]
Check out the documentation on forecasting [here](https://lavinei.github.io/pybats/forecast.html).

Short answer: Path forecast takes into account the dependence across the forecast horizon, while marginal forecasting does not. This is important if, for instance, you take the sum of the forecast samples to get a forecast for the total over multiple time steps.

**Comment by artrune** [comment]
Thank you very much, both for the quick explanation and for the link to the forecast documentation (I actually struggled a bit finding more docs about pybats so this comes super handy)
